#!/bin/sh

if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

LOGFILE=~/bash_boost.log
cat > $LOGFILE <<< "--- Attempting to boost your bash non login..."

cat >> $LOGFILE <<< "history boost..."
source ~/.history

cat >> $LOGFILE <<< "aliases..."
source ~/.aliases

cat >> $LOGFILE <<< "environment..."
source ~/.os_specific/loader

cat >> $LOGFILE <<< "user specific boost..."
source ~/.user_specific/loader

cat >> $LOGFILE <<< "--- Boost process for non login shell Complete!"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export PATH="$PATH:/Users/andy/mongo/bin"

export PATH=${PATH}:"/Library/PostgreSQL/9.5/bin"

export NVM_DIR="/Users/andy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
